namespace Homassy.API.Enums
{
    /// <summary>
    /// Currency codes including fiat currencies (ISO 4217) and cryptocurrencies
    /// Source: https://latest.currency-api.pages.dev/v1/currencies.json
    /// </summary>
    public enum Currency
    {
        OneInch = 0, // 1inch
        Aave = 1, // Aave
        Ada = 2, // Cardano
        Aed = 3, // Emirati Dirham
        Afn = 4, // Afghan Afghani
        Agix = 5, // SingularityNET
        Akt = 6, // Akash Network
        Algo = 7, // Algorand
        All = 8, // Albanian Lek
        Amd = 9, // Armenian Dram
        Amp = 10, // Amp
        Ang = 11, // Dutch Guilder
        Aoa = 12, // Angolan Kwanza
        Ape = 13, // ApeCoin
        Apt = 14, // Aptos
        Ar = 15, // Arweave
        Arb = 16, // Arbitrum
        Ars = 17, // Argentine Peso
        Atom = 18, // Cosmos
        Ats = 19, // Austrian Schilling
        Aud = 20, // Australian Dollar
        Avax = 21, // Avalanche
        Awg = 22, // Aruban or Dutch Guilder
        Axs = 23, // Axie Infinity
        Azm = 24, // Azerbaijani Manat
        Azn = 25, // Azerbaijan Manat
        Bake = 26, // BakeryToken
        Bam = 27, // Bosnian Convertible Mark
        Bat = 28, // Basic Attention Token
        Bbd = 29, // Barbadian or Bajan Dollar
        Bch = 30, // Bitcoin Cash
        Bdt = 31, // Bangladeshi Taka
        Bef = 32, // Belgian Franc
        Bgn = 33, // Bulgarian Lev
        Bhd = 34, // Bahraini Dinar
        Bif = 35, // Burundian Franc
        Bmd = 36, // Bermudian Dollar
        Bnb = 37, // Binance Coin
        Bnd = 38, // Bruneian Dollar
        Bob = 39, // Bolivian Bolíviano
        Brl = 40, // Brazilian Real
        Bsd = 41, // Bahamian Dollar
        Bsv = 42, // Bitcoin SV
        Bsw = 43, // Biswap
        Btc = 44, // Bitcoin
        Btcb = 45, // Bitcoin BEP2
        Btg = 46, // Bitcoin Gold
        Btn = 47, // Bhutanese Ngultrum
        Btt = 48, // BitTorrent
        Busd = 49, // Binance USD
        Bwp = 50, // Botswana Pula
        Byn = 51, // Belarusian Ruble
        Byr = 52, // Belarusian Ruble
        Bzd = 53, // Belizean Dollar
        Cad = 54, // Canadian Dollar
        Cake = 55, // PancakeSwap
        Cdf = 56, // Congolese Franc
        Celo = 57, // Celo
        Cfx = 58, // Conflux
        Chf = 59, // Swiss Franc
        Chz = 60, // Chiliz
        Clp = 61, // Chilean Peso
        Cnh = 62, // Chinese Yuan Renminbi Offshore
        Cny = 63, // Chinese Yuan Renminbi
        Comp = 64, // Compound
        Cop = 65, // Colombian Peso
        Crc = 66, // Costa Rican Colon
        Cro = 67, // Crypto.com Chain
        Crv = 68, // Curve DAO Token
        Cspr = 69, // Casper
        Cuc = 70, // Cuban Convertible Peso
        Cup = 71, // Cuban Peso
        Cve = 72, // Cape Verdean Escudo
        Cvx = 73, // Convex Finance
        Cyp = 74, // Cypriot Pound
        Czk = 75, // Czech Koruna
        Dai = 76, // DAI
        Dash = 77, // Digital Cash
        Dcr = 78, // Decred
        Dem = 79, // German Deutsche Mark
        Dfi = 80, // DfiStarter
        Djf = 81, // Djiboutian Franc
        Dkk = 82, // Danish Krone
        Doge = 83, // Dogecoin
        Dop = 84, // Dominican Peso
        Dot = 85, // Polkadot
        Dydx = 86, // dYdX
        Dzd = 87, // Algerian Dinar
        Eek = 88, // Estonian Kroon
        Egld = 89, // Elrond
        Egp = 90, // Egyptian Pound
        Enj = 91, // Enjin Coin
        Eos = 92, // EOS
        Ern = 93, // Eritrean Nakfa
        Esp = 94, // Spanish Peseta
        Etb = 95, // Ethiopian Birr
        Etc = 96, // Ethereum Classic
        Eth = 97, // Ethereum
        Eur = 98, // Euro
        Eurc = 99, // 
        Fei = 100, // Fei USD
        Fil = 101, // Filecoin
        Fim = 102, // Finnish Markka
        Fjd = 103, // Fijian Dollar
        Fkp = 104, // Falkland Island Pound
        Flow = 105, // Flow
        Flr = 106, // FLARE
        Frax = 107, // Frax
        Frf = 108, // French Franc
        Ftt = 109, // FarmaTrust
        Gala = 110, // Gala
        Gbp = 111, // British Pound
        Gel = 112, // Georgian Lari
        Ggp = 113, // Guernsey Pound
        Ghc = 114, // Ghanaian Cedi
        Ghs = 115, // Ghanaian Cedi
        Gip = 116, // Gibraltar Pound
        Gmd = 117, // Gambian Dalasi
        Gmx = 118, // Goldmaxcoin
        Gnf = 119, // Guinean Franc
        Gno = 120, // Gnosis
        Grd = 121, // Greek Drachma
        Grt = 122, // The Graph
        Gt = 123, // GateToken
        Gtq = 124, // Guatemalan Quetzal
        Gusd = 125, // Gemini US Dollar
        Gyd = 126, // Guyanese Dollar
        Hbar = 127, // Hedera
        Hkd = 128, // Hong Kong Dollar
        Hnl = 129, // Honduran Lempira
        Hnt = 130, // Helium
        Hot = 131, // Hydro Protocol
        Hrk = 132, // Croatian Kuna
        Ht = 133, // Huobi Token
        Htg = 134, // Haitian Gourde
        Huf = 135, // Hungarian Forint
        Icp = 136, // Internet Computer
        Idr = 137, // Indonesian Rupiah
        Iep = 138, // Irish Pound
        Ils = 139, // Israeli Shekel
        Imp = 140, // Isle of Man Pound
        Imx = 141, // Immutable X
        Inj = 142, // Injective
        Inr = 143, // Indian Rupee
        Iqd = 144, // Iraqi Dinar
        Irr = 145, // Iranian Rial
        Isk = 146, // Icelandic Krona
        Itl = 147, // Italian Lira
        Jep = 148, // Jersey Pound
        Jmd = 149, // Jamaican Dollar
        Jod = 150, // Jordanian Dinar
        Jpy = 151, // Japanese Yen
        Kas = 152, // 
        Kava = 153, // Kava
        Kcs = 154, // Kucoin
        Kda = 155, // Kadena
        Kes = 156, // Kenyan Shilling
        Kgs = 157, // Kyrgyzstani Som
        Khr = 158, // Cambodian Riel
        Klay = 159, // Klaytn
        Kmf = 160, // Comorian Franc
        Knc = 161, // Kyber Network Crystals
        Kpw = 162, // North Korean Won
        Krw = 163, // South Korean Won
        Ksm = 164, // Kusama
        Kwd = 165, // Kuwaiti Dinar
        Kyd = 166, // Caymanian Dollar
        Kzt = 167, // Kazakhstani Tenge
        Lak = 168, // Lao Kip
        Lbp = 169, // Lebanese Pound
        Ldo = 170, // Lido DAO Token
        Leo = 171, // LEOcoin
        Link = 172, // Chainlink
        Lkr = 173, // Sri Lankan Rupee
        Lrc = 174, // Loopring
        Lrd = 175, // Liberian Dollar
        Lsl = 176, // Basotho Loti
        Ltc = 177, // Litecoin
        Ltl = 178, // Lithuanian Litas
        Luf = 179, // Luxembourg Franc
        Luna = 180, // Terra
        Lunc = 181, // 
        Lvl = 182, // Latvian Lat
        Lyd = 183, // Libyan Dinar
        Mad = 184, // Moroccan Dirham
        Mana = 185, // Mana Coin Decentraland
        Mbx = 186, // MobieCoin
        Mdl = 187, // Moldovan Leu
        Mga = 188, // Malagasy Ariary
        Mgf = 189, // Malagasy Franc
        Mina = 190, // Mina
        Mkd = 191, // Macedonian Denar
        Mkr = 192, // Maker
        Mmk = 193, // Burmese Kyat
        Mnt = 194, // Mongolian Tughrik
        Mop = 195, // Macau Pataca
        Mro = 196, // Mauritanian Ouguiya
        Mru = 197, // Mauritanian Ouguiya
        Mtl = 198, // Maltese Lira
        Mur = 199, // Mauritian Rupee
        Mvr = 200, // Maldivian Rufiyaa
        Mwk = 201, // Malawian Kwacha
        Mxn = 202, // Mexican Peso
        Mxv = 203, // 
        Myr = 204, // Malaysian Ringgit
        Mzm = 205, // Mozambican Metical
        Mzn = 206, // Mozambican Metical
        Nad = 207, // Namibian Dollar
        Near = 208, // NEAR Protocol
        Neo = 209, // NEO
        Nexo = 210, // NEXO
        Nft = 211, // NFT
        Ngn = 212, // Nigerian Naira
        Nio = 213, // Nicaraguan Cordoba
        Nlg = 214, // Dutch Guilder
        Nok = 215, // Norwegian Krone
        Npr = 216, // Nepalese Rupee
        Nzd = 217, // New Zealand Dollar
        Okb = 218, // Okex
        Omr = 219, // Omani Rial
        One = 220, // Menlo One
        Op = 221, // Optimism
        Ordi = 222, // 
        Pab = 223, // Panamanian Balboa
        Paxg = 224, // PAX Gold
        Pen = 225, // Peruvian Sol
        Pepe = 226, // 
        Pgk = 227, // Papua New Guinean Kina
        Php = 228, // Philippine Peso
        Pi = 229, // Plian
        Pkr = 230, // Pakistani Rupee
        Pln = 231, // Polish Zloty
        Pol = 232, // Proof Of Liquidity
        Pte = 233, // Portuguese Escudo
        Pyg = 234, // Paraguayan Guarani
        Qar = 235, // Qatari Riyal
        Qnt = 236, // Quant
        Qtum = 237, // QTUM
        Rol = 238, // Romanian Leu
        Ron = 239, // Romanian Leu
        Rpl = 240, // Rocket Pool
        Rsd = 241, // Serbian Dinar
        Rub = 242, // Russian Ruble
        Rune = 243, // THORChain (ERC20)
        Rvn = 244, // Ravencoin
        Rwf = 245, // Rwandan Franc
        Sand = 246, // The Sandbox
        Sar = 247, // Saudi Arabian Riyal
        Sbd = 248, // Solomon Islander Dollar
        Scr = 249, // Seychellois Rupee
        Sdd = 250, // Sudanese Dinar
        Sdg = 251, // Sudanese Pound
        Sek = 252, // Swedish Krona
        Sgd = 253, // Singapore Dollar
        Shib = 254, // Shiba Inu
        Shp = 255, // Saint Helenian Pound
        Sit = 256, // Slovenian Tolar
        Skk = 257, // Slovak Koruna
        Sle = 258, // Sierra Leonean Leone
        Sll = 259, // Sierra Leonean Leone
        Snx = 260, // Synthetix Network
        Sol = 261, // Solana
        Sos = 262, // Somali Shilling
        Spl = 263, // Seborgan Luigino
        Srd = 264, // Surinamese Dollar
        Srg = 265, // Surinamese Guilder
        Ssp = 266, // South Sudanese Pound
        Std = 267, // Sao Tomean Dobra
        Stn = 268, // Sao Tomean Dobra
        Stx = 269, // Stacks
        Sui = 270, // Sui
        Svc = 271, // Salvadoran Colon
        Syp = 272, // Syrian Pound
        Szl = 273, // Swazi Lilangeni
        Thb = 274, // Thai Baht
        Theta = 275, // Theta
        Tjs = 276, // Tajikistani Somoni
        Tmm = 277, // Turkmenistani Manat
        Tmt = 278, // Turkmenistani Manat
        Tnd = 279, // Tunisian Dinar
        Ton = 280, // Tokamak Network
        Top = 281, // Tongan Pa'anga
        Trl = 282, // 
        Trx = 283, // TRON
        Try = 284, // Turkish Lira
        Ttd = 285, // Trinidadian Dollar
        Tusd = 286, // True USD
        Tvd = 287, // Tuvaluan Dollar
        Twd = 288, // Taiwan New Dollar
        Twt = 289, // Trust Wallet Token
        Tzs = 290, // Tanzanian Shilling
        Uah = 291, // Ukrainian Hryvnia
        Ugx = 292, // Ugandan Shilling
        Uni = 293, // Uniswap
        Usd = 294, // US Dollar
        Usdc = 295, // USDC
        Usdd = 296, // 
        Usdp = 297, // USDP Stablecoin
        Usdt = 298, // Tether
        Uyu = 299, // Uruguayan Peso
        Uzs = 300, // Uzbekistani Som
        Val = 301, // Vatican City Lira
        Veb = 302, // Venezuelan Bolívar
        Ved = 303, // 
        Vef = 304, // Venezuelan Bolívar
        Ves = 305, // Venezuelan Bolívar
        Vet = 306, // Vechain
        Vnd = 307, // Vietnamese Dong
        Vuv = 308, // Ni-Vanuatu Vatu
        Waves = 309, // Waves
        Wemix = 310, // WEMIX
        Woo = 311, // WOO Network
        Wst = 312, // Samoan Tala
        Xaf = 313, // Central African CFA Franc BEAC
        Xag = 314, // Silver Ounce
        Xau = 315, // Gold Ounce
        Xaut = 316, // Tether Gold
        Xbt = 317, // 
        Xcd = 318, // East Caribbean Dollar
        Xcg = 319, // Xchange
        Xch = 320, // Chia
        Xdc = 321, // XDC Network
        Xdr = 322, // IMF Special Drawing Rights
        Xec = 323, // Eternal Coin
        Xem = 324, // NEM
        Xlm = 325, // Stellar Lumen
        Xmr = 326, // Monero
        Xof = 327, // CFA Franc
        Xpd = 328, // Palladium Ounce
        Xpf = 329, // CFP Franc
        Xpt = 330, // Platinum Ounce
        Xrp = 331, // Ripple
        Xtz = 332, // Tezos
        Yer = 333, // Yemeni Rial
        Zar = 334, // South African Rand
        Zec = 335, // ZCash
        Zil = 336, // Zilliqa
        Zmk = 337, // Zambian Kwacha
        Zmw = 338, // Zambian Kwacha
        Zwd = 339, // Zimbabwean Dollar
        Zwg = 340, // 
        Zwl = 341  // Zimbabwean Dollar
    }
}
