/**
 * GENERATED by scripts/sync-product-category.mjs — do not edit by hand.
 *
 * Which ProductCategoryGroup each ProductCategory value belongs to. The grouping
 * is presentation-only (it drives the grouped category pickers); the API neither
 * knows nor stores it. Ranges may cover numbers no member uses yet.
 */

import { ProductCategoryGroup } from '~/types/enums'

/** Groups in the order the pickers should show them. */
export const PRODUCT_CATEGORY_GROUP_ORDER: ProductCategoryGroup[] = [
  ProductCategoryGroup.Other,
  ProductCategoryGroup.Food,
  ProductCategoryGroup.Health,
  ProductCategoryGroup.PersonalCare,
  ProductCategoryGroup.Bathroom,
  ProductCategoryGroup.Cleaning,
  ProductCategoryGroup.PestControl,
  ProductCategoryGroup.Kitchen,
  ProductCategoryGroup.Appliances,
  ProductCategoryGroup.Home,
  ProductCategoryGroup.HomeImprovement,
  ProductCategoryGroup.Tools,
  ProductCategoryGroup.Garden,
  ProductCategoryGroup.Automotive,
  ProductCategoryGroup.Winter,
  ProductCategoryGroup.Electronics,
  ProductCategoryGroup.SmartHome,
  ProductCategoryGroup.Clothing,
  ProductCategoryGroup.Entertainment,
  ProductCategoryGroup.SportsAndLeisure,
  ProductCategoryGroup.Pets,
  ProductCategoryGroup.Office,
  ProductCategoryGroup.BabyAndKids,
  ProductCategoryGroup.PartyAndSeasonal,
  ProductCategoryGroup.Travel,
  ProductCategoryGroup.Safety,
  ProductCategoryGroup.Valuables
]

const PRODUCT_CATEGORY_GROUP_RANGES: Record<ProductCategoryGroup, [number, number][]> = {
  [ProductCategoryGroup.Other]: [[0, 0]],
  [ProductCategoryGroup.Food]: [[1, 49]],
  [ProductCategoryGroup.Health]: [[50, 69], [500, 549]],
  [ProductCategoryGroup.PersonalCare]: [[70, 89], [926, 929]],
  [ProductCategoryGroup.Bathroom]: [[900, 925]],
  [ProductCategoryGroup.Cleaning]: [[90, 109], [270, 289]],
  [ProductCategoryGroup.PestControl]: [[290, 299]],
  [ProductCategoryGroup.Kitchen]: [[110, 119], [340, 359]],
  [ProductCategoryGroup.Appliances]: [[320, 331], [360, 379]],
  [ProductCategoryGroup.Home]: [[120, 139]],
  [ProductCategoryGroup.HomeImprovement]: [[570, 629], [930, 999]],
  [ProductCategoryGroup.Tools]: [[140, 159], [842, 889]],
  [ProductCategoryGroup.Garden]: [[160, 169], [630, 699], [820, 841]],
  [ProductCategoryGroup.Automotive]: [[180, 189], [1000, 1029]],
  [ProductCategoryGroup.Winter]: [[1030, 1039]],
  [ProductCategoryGroup.Electronics]: [[170, 179], [380, 409]],
  [ProductCategoryGroup.SmartHome]: [[300, 319]],
  [ProductCategoryGroup.Clothing]: [[190, 209]],
  [ProductCategoryGroup.Entertainment]: [[210, 219], [550, 569], [800, 809]],
  [ProductCategoryGroup.SportsAndLeisure]: [[700, 799]],
  [ProductCategoryGroup.Pets]: [[220, 229]],
  [ProductCategoryGroup.Office]: [[230, 249]],
  [ProductCategoryGroup.BabyAndKids]: [[250, 269], [810, 819]],
  [ProductCategoryGroup.PartyAndSeasonal]: [[440, 459]],
  [ProductCategoryGroup.Travel]: [[460, 479]],
  [ProductCategoryGroup.Safety]: [[480, 499]],
  [ProductCategoryGroup.Valuables]: [[1040, 1049]]
}

/**
 * The group a raw category value belongs to, or `null` for a value this build
 * does not know (an older row pointing at a since-removed category).
 */
export function getProductCategoryGroup(value: number): ProductCategoryGroup | null {
  for (const group of PRODUCT_CATEGORY_GROUP_ORDER) {
    for (const [from, to] of PRODUCT_CATEGORY_GROUP_RANGES[group]) {
      if (value >= from && value <= to) return group
    }
  }
  return null
}
